# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: ["elixir:1.11"]   

    container:
      image: ${{ matrix.elixir }}  

    steps:
    - uses: actions/checkout@v4
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Hex and Rebar
      run: mix local.hex --force && mix local.rebar --force
    - name: Install dependencies
      run: mix deps.get
    - name: Compile
      run: mix compile
    - name: Run tests
      run: MIX_ENV=test mix coveralls.xml
    - name: Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: cover/excoveralls.xml
